### ISSUE TITLE
API documentation is inaccurate on date_received_max parameter

### ISSUE THREAD

**Issue by azelk** [cfpb/ccdb5-api#104]
It says that 
> date_received_max
> string
> (query)
> Return results with date < date_received_max (i.e. 2017-03-04)

But in fact it queries with `date <= date_received_max`, for instance:
 >?date_received_min=2012-01-01&date_received_max=2012-01-01&format=default&size=50

Returns 14 records with date_received = 2012-01-01

I hope that this behavior won't change and the documentation will be fixed accordingly

**Comment by sephcoster** [comment]
Thanks @azelk - we're updating our documentation to indicate the precise behavior.

**Comment by AdamZarger** [comment]
Resolved in PR #110
