### ISSUE TITLE
API limitations are not allowing for a meaningful usage

### ISSUE THREAD

**Issue by azelk** [cfpb/ccdb5-api#105]
Queries' results are cut to a maximum of 100 records and parameter `from` doesn't work which prohibits most meaningful applications of the API presented

**Comment by JeffreyMFarley** [comment]
Do you have a sample URL/query that demonstrates this defect?

**Comment by azelk** [comment]
Seems to be working by now

**Comment by sephcoster** [comment]
Thanks! 

If you do encounter an issue with this again please send us the URL and we will re-open / investigate.
