### ISSUE TITLE
Swagger documentation on `/?field` appears to be incorrect.

### ISSUE THREAD

**Issue by kevin-lindsay-1** [cfpb/ccdb5-api#122]
Per the documentation:
```
Search by particular field. If this parameter is not specified, default behavior
will return only complaints with narratives.
```

Although, the first `hit` when you perform a search with no criteria is the complaint with ID `2662569`, which does not have a narrative.

**Comment by JeffreyMFarley** [comment]
Thanks for bringing this to our attention. We'll fix the documents to reflect the current behavior
