### ISSUE TITLE
My insurance card hasnt came in but i have the number...its saying not active..

### ISSUE THREAD

**Issue by nadia-619** [cfpb/ccdb5-api#165]

**Comment by Scotchester** [comment]
Hi Nadia,

If you would like to submit a complaint about a financial product or service, please go to: https://www.consumerfinance.gov/complaint/

**Comment by ascott1** [comment]
Hi @nadia-619, here is your full list of options for outreach, in case it is helpful:

To submit a complaint about a consumer financial product or service:
- Visit https://www.consumerfinance.gov/complaint
- Call us toll-free at (855) 411-2372
- Mail your complaint to:

  Consumer Financial Protection Bureau
  P.O. Box 2900                                                                                                                                      
  Clinton, IA 52733

To talk to someone about your issue or ask a question, call us toll-free at (855) 411-2372
