### ISSUE TITLE
Hits.total for the `/` endpoint does not parse as an integer

### ISSUE THREAD

**Issue by mwalker9** [cfpb/ccdb5-api#179]
There seems to be a discrepancy between the Swagger documentation and the actual response object.  The documentation indicates that Hits.total should parse as an integer.

In practice, for the `/` endpoint, I found that hits.total is an object that looks something like this:

```
{
            "value": 3198,
            "relation": "eq"
}
```

Example API call: 

www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?date_received_max=2021-09-15&date_received_min=2021-09-14

**Comment by higs4281** [comment]
@mwalker9 
FYI, our code always requests [`track_total_hits`](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-your-data.html#track-total-hits), which is less efficient but always returns the true hit count, even above 10,000 hits. 
So `hits.total.value` should return what you were used to seeing in `hits.total`, and you can ignore Elasticsearch's "relation" value.
