### ISSUE TITLE
Suggest endpoint is not suggesting

### ISSUE THREAD

**Issue by JeffreyMFarley** [cfpb/ccdb5-api#20]
It seems the current implementation is not behaving as expected.

Steps to reproduce:
1. `/_suggest/?text=Mort&size=6`
2. Returns
```
{
"sgg": [
  {
   "text": "Mort",
   "length": 4, 
   "options": [],
   "offset": 0
  }
 ],
}
```
I would expect "mortgage" as one example

**Comment by amymok** [comment]
https://github.com/cfpb/ccdb-data-pipeline/pull/12
https://github.com/cfpb/ccdb5-api/pull/24

These two PRs should fix the issue.
