### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by JeffreyMFarley** [cfpb/ccdb5-api#27]
http://localhost:8000/data-research/consumer-complaints/search/api/v1/?product=Debt%20collection&size=10&sort=relevance_desc

produces the same set as 

http://localhost:8000/data-research/consumer-complaints/search/api/v1/?product=Debt%20collection&size=10&sort=relevance_desc&frm=20

But with `frm=20` that shouldn't be the case

**Comment by kanhiya94** [comment]
Add **search_after** in **params**

Like this -> search_after=1639155600000_4998992

Get the value of **search_after** from $.hits.hits[index].sort[0]+"_"+$.hits.hits[index].sort[1]
