### ISSUE TITLE
README missing documentation on how to load data

### ISSUE THREAD

**Issue by wpears** [cfpb/ccdb5-api#71]
The first instructions in the setup section of the README are:
```
This repository assumes that you have an instance of elasticsearch running with complaint data set up and running.
```

I believe it would help get users off the ground if you could be more specific here, with links to any public data or even the expected schema of the data.

**Comment by champain** [comment]
Agreed about the complaint data.

**Comment by chosak** [comment]
I just came here to create this same issue.

I was able to use the [ccdb-data-pipeline](https://github.com/cfpb/ccdb-data-pipeline) repo to load public data into a local Elasticsearch, although currently it requires [one minor code change](https://github.com/cfpb/ccdb-data-pipeline/issues/20). Running that pipeline creates an index with whatever name you specify and a [document type of "complaint"](https://github.com/cfpb/ccdb-data-pipeline/blob/f145a63a406542f59eee099c95f02402b71675a0/run_pipeline.py#L9). Notably this differs from the default document type assumed in code which is "complaint-doctype", which requires setting the `COMPLAINT_DOC_TYPE` environment variable to get this repo to work.

I'm going to rename this issue to more specifically request improved documentation in the README.

**Comment by higs4281** [comment]
Install and loading instructions are being updated in the [INSTALL doc](https://github.com/cfpb/ccdb-data-pipeline/blob/update-installation-docs/INSTALL.md) of a related repository, [ccdb-data-pipeline](https://github.com/cfpb/ccdb-data-pipeline), where the code for loading lives. 

Closing the issue on this repo.
