### ISSUE TITLE
Questions about `catch_es_error` decorator's status code and response body

### ISSUE THREAD

**Issue by acrewdson** [cfpb/ccdb5-api#74]
When doing some testing against a cf.gov environment that could not talk to Elasticsearch, I saw the following error at `/data-research/consumer-complaints/search/api/v1/?field=all&size=25&sort=created_date_desc`:

```
Elasticsearch error: <urllib3.connection.HTTPConnection object at 0x7f5558fef650>: Failed to establish a new connection: [Errno 111] Connection refused
```

This was in a non-debug environment where I would not expect to see a raw exception leaking into a response like that. I thought I'd open an issue in case this is something that could be adjusted.

I'm also wondering if a `400` (see [here](https://github.com/cfpb/ccdb5-api/blob/master/complaint_search/decorators.py#L11)) is appropriate in this scenario, since it seems more like a `500` situation to me.

**Comment by JeffreyMFarley** [comment]
In the internal version we change the code to be [424 - Failed Dependency](https://httpstatusdogs.com/424-failed-dependency)
