### ISSUE TITLE
Update django-flags version to match cfgov

### ISSUE THREAD

**Issue by wpears** [cfpb/ccdb5-api#82]
https://github.com/cfpb/cfgov-refresh/blob/master/requirements/libraries.txt#L8

**Comment by schbetsy** [comment]
CCDB's [setup.py](https://github.com/cfpb/ccdb5-api/blame/master/setup.py) requires `'django-flags>=4.0.1,<5'`. Since cfgov-refresh uses version 4.2.2, this is compatible.
